### ISSUE TITLE
Error: The id "0001xxxxxx72." is invalid. Ids are not allowed to end in "."

### ISSUE THREAD

**Issue by tholterhus** [Grizzelbee/ioBroker.mielecloudservice#281]
after connecting with miele, the adapter throws an exeption:

2022-08-09 10:26:43.250  - error: host.iobroker Caught by controller[7]:     at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.mielecloudservice/source/mieleTools.js:1922:68)
2022-08-09 10:26:43.251  - error: host.iobroker Caught by controller[7]:     at processImmediate (internal/timers.js:466:21)
2022-08-09 10:26:43.251  - error: host.iobroker Caught by controller[8]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-08-09 10:26:43.251  - error: host.iobroker Caught by controller[9]: Error: The id "0001xxxxxx72." is invalid. Ids are not allowed to end in "."
2022-08-09 10:26:43.251  - error: host.iobroker Caught by controller[9]:     at Utils.validateId (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/utils.ts:215:23)
2022-08-09 10:26:43.251  - error: host.iobroker Caught by controller[9]:     at Mielecloudservice.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:6309:23)
2022-08-09 10:26:43.251  - error: host.iobroker Caught by controller[9]:     at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.mielecloudservice/source/mieleTools.js:1922:68)
2022-08-09 10:26:43.252  - error: host.iobroker Caught by controller[9]:     at processImmediate (internal/timers.js:466:21)
2022-08-09 10:26:43.252  - error: host.iobroker instance system.adapter.mielecloudservice.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-08-09 10:26:43.252  - info: host.iobroker Restart adapter system.adapter.mielecloudservice.0 because enabled
2022-08-09 10:26:43.252  - warn: host.iobroker Do not restart adapter system.adapter.mielecloudservice.0 because restart loop detected
2022-08-09 10:29:08.601  - info: host.iobroker "system.adapter.mielecloudservice.0" disabled
2022-08-09 10:29:55.509  - info: admin.0 (2254) Adapter rating updated

Objects are populated, but due to the exception the adapter is terminated

![image](https://user-images.githubusercontent.com/37276968/183621706-7cba820e-dcc7-4b16-8ffd-f3834418982d.png)

**Comment by tholterhus** [comment]
v6.3.2 that is, installed on ioBroker v5.3.8

**Comment by Grizzelbee** [comment]
This issue is already known and investigated. 
It's an issue with the Miele API. There values for key_localized and value_localized aren't populated by the API. 
I already asked Miele if they fix it or if I need to find a workaround - but I assume that Miele will fix it.

Thread in german ioBroker Forum: https://forum.iobroker.net/post/839913

**Comment by chrispi68** [comment]
Same problem here.

**Comment by Nunmalfix** [comment]
Same problem - waiting for Miele to fix it...

**Comment by Grizzelbee** [comment]
New knowledge:
* only SSE is affected -> data polling works
* all localization languages seem to be affected (only german and english have been testet)

**Comment by schoebelh** [comment]
Seams that is solved by miele - adapter starts again without errors.

**Comment by Grizzelbee** [comment]
Has been fixed my Miele. 
Confirmed by currently 3 Users.
