### ISSUE TITLE
start of adapter fails with "oauth.client is not a function"

### ISSUE THREAD

**Issue by Grizzelbee** [Grizzelbee/ioBroker.mielecloudservice#359]
2023-04-05 19:30:56.195 - info: mielecloudservice.0 (1078) starting. Version 6.5.0-beta2 (non-npm: Grizzelbee/ioBroker.mielecloudservice) in /usr/local/iobroker/node_modules/iobroker.mielecloudservice, node: v16.14.2, js-controller: 4.0.24
2023-04-05 19:30:56.199 - info: mielecloudservice.0 (1078) Login attempt #1 @Miele-API
2023-04-05 19:30:56.200 - error: mielecloudservice.0 (1078) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-04-05 19:30:56.200 - error: mielecloudservice.0 (1078) unhandled promise rejection: oauth.client is not a function
2023-04-05 19:30:56.201 - error: mielecloudservice.0 (1078) TypeError: oauth.client is not a function
at /usr/local/iobroker/node_modules/iobroker.mielecloudservice/source/mieleTools.js:85:49
at new Promise ()
at Object.module.exports.getAuth (/usr/local/iobroker/node_modules/iobroker.mielecloudservice/source/mieleTools.js:82:12)
at /usr/local/iobroker/node_modules/iobroker.mielecloudservice/main.js:239:49
at Mielecloudservice.onReady (/usr/local/iobroker/node_modules/iobroker.mielecloudservice/main.js:237:17)
2023-04-05 19:30:56.201 - error: mielecloudservice.0 (1078) oauth.client is not a function
2023-04-05 19:30:56.204 - info: mielecloudservice.0 (1078) terminating
2023-04-05 19:30:56.204 - debug: mielecloudservice.0 (1078) Plugin sentry destroyed
2023-04-05 19:30:56.204 - warn: mielecloudservice.0 (1078) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-04-05 19:30:56.725 - error: host.Mac-mini.fritz.box Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-04-05 19:30:56.725 - error: host.Mac-mini.fritz.box Caught by controller[0]: TypeError: oauth.client is not a function
2023-04-05 19:30:56.725 - error: host.Mac-mini.fritz.box Caught by controller[0]: at /usr/local/iobroker/node_modules/iobroker.mielecloudservice/source/mieleTools.js:85:49
2023-04-05 19:30:56.725 - error: host.Mac-mini.fritz.box Caught by controller[0]: at new Promise ()
2023-04-05 19:30:56.725 - error: host.Mac-mini.fritz.box Caught by controller[0]: at Object.module.exports.getAuth (/usr/local/iobroker/node_modules/iobroker.mielecloudservice/source/mieleTools.js:82:12)
2023-04-05 19:30:56.725 - error: host.Mac-mini.fritz.box Caught by controller[0]: at /usr/local/iobroker/node_modules/iobroker.mielecloudservice/main.js:239:49
2023-04-05 19:30:56.726 - error: host.Mac-mini.fritz.box Caught by controller[0]: at Mielecloudservice.onReady (/usr/local/iobroker/node_modules/iobroker.mielecloudservice/main.js:237:17)
2023-04-05 19:30:56.726 - error: host.Mac-mini.fritz.box instance system.adapter.mielecloudservice.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-04-05 19:30:56.726 - info: host.Mac-mini.fritz.box Restart adapter system.adapter.mielecloudservice.0 because enabled
2023-04-05 19:30:56.726 - warn: host.Mac-mini.fritz.box Do not restart adapter system.adapter.mielecloudservice.0 because restart loop detected

**Comment by Grizzelbee** [comment]
this bug is mentioned in #356  and #343
