### ISSUE TITLE
Error onUnload

### ISSUE THREAD

**Issue by Grizzelbee** [Grizzelbee/ioBroker.mielecloudservice#58]
Service | Date&Time | Loglevel | message
-- | -- | -- | --
mielecloudservice.0 | 2021-01-11 10:52:29.165 | error | at processImmediate (internal/timers.js:461:21)
mielecloudservice.0 | 2021-01-11 10:52:29.165 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:236:41)
mielecloudservice.0 | 2021-01-11 10:52:29.165 | error | at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5215:29)
mielecloudservice.0 | 2021-01-11 10:52:29.165 | error | at stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8257:29)
mielecloudservice.0 | 2021-01-11 10:52:29.165 | error | at Object.unload (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:54:21)
mielecloudservice.0 | 2021-01-11 10:52:29.165 | error | at APILogOff (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:871:67)
mielecloudservice.0 | 2021-01-11 10:52:29.165 | error | (18422) ReferenceError: err is not defined
mielecloudservice.0 | 2021-01-11 10:52:29.164 | error | (18422) unhandled promise rejection: err is not defined
mielecloudservice.0 | 2021-01-11 10:52:29.160 | error | at processImmediate (internal/timers.js:461:21)
mielecloudservice.0 | 2021-01-11 10:52:29.160 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:236:41)
mielecloudservice.0 | 2021-01-11 10:52:29.160 | error | at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5215:29)
mielecloudservice.0 | 2021-01-11 10:52:29.160 | error | at stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8257:29)
mielecloudservice.0 | 2021-01-11 10:52:29.160 | error | at Object.unload (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:51:21)
mielecloudservice.0 | 2021-01-11 10:52:29.160 | error | at APILogOff (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:871:67)
mielecloudservice.0 | 2021-01-11 10:52:29.160 | error | (18422) ReferenceError: err is not defined
mielecloudservice.0 | 2021-01-11 10:52:29.154 | error | (18422) unhandled promise rejection: err is not defined
mielecloudservice.0 | 2021-01-11 10:52:29.141 | info | (18422) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mielecloudservice.0 | 2021-01-11 10:52:29.141 | info | (18422) terminating
mielecloudservice.0 | 2021-01-11 10:52:29.140 | info | (18422) Unloading MieleCloudService...
mielecloudservice.0 | 2021-01-11 10:52:29.138 | info | (18422) Clearing Timeout: pollTimeout
mielecloudservice.0 | 2021-01-11 10:52:29.137 | info | (18422) Got terminate signal TERMINATE_YOURSELF

**Comment by Grizzelbee** [comment]
Fehler wurde mit Version 2.0.3 behoben.
